[package]
name = "protobench"
description = "Multi-party computation experimentation library"
version = "0.0.1"
authors = ["Jelle Vos <J.V.Vos@tudelft.nl>"]
edition = "2018"
license = "MIT"
homepage = "https://github.com/jellevos/protobench"
repository = "https://github.com/jellevos/protobench"
readme = "README.md"

[dependencies]
